# Generated by Django 4.1 on 2022-08-29 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djpaddle', '0004_auto_20210119_0436'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='instalments',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
